import React from "react";
import {
  RotateCcw,
  Download,
  Eye,
  ShieldCheck,
  AlertTriangle,
  CheckCircle2,
  Bot,
  Camera,
} from "lucide-react";

export default function FinalVerdict({
  currentData,
  onAnalyzeAnother,
  onDownloadReport,
  onViewFullAnalysis
}) {
  const isSynthetic = Boolean(currentData.isAIGenerated);
  const synthScore = currentData.syntheticConfidence ?? currentData.confidence;
  const realScore = currentData.realConfidence ?? (100 - currentData.confidence);

  return (
    <div className="w-full max-w-4xl mx-auto mt-10 mb-12 animate-in fade-in slide-in-from-bottom-4 duration-300">

      {/* Centered Large Floating Card */}
      <div className={`rounded-3xl bg-white p-8 sm:p-12 border shadow-sm relative overflow-hidden ${
        isSynthetic ? "border-[#c15f3c]/30" : "border-emerald-300/30"
      }`}>

        {/* Top accent bar */}
        <div className={`absolute top-0 left-0 right-0 h-1 ${
          isSynthetic ? "bg-gradient-to-r from-[#c15f3c] to-amber-400" : "bg-gradient-to-r from-emerald-500 to-emerald-700"
        }`} />

        {/* Top icon */}
        <div className={`relative mx-auto mb-6 w-16 h-16 rounded-2xl border flex items-center justify-center shadow-sm ${
          isSynthetic
            ? "bg-[#c15f3c]/10 border-[#c15f3c]/30 text-[#c15f3c]"
            : "bg-emerald-50 border-emerald-300 text-emerald-700"
        }`}>
          {isSynthetic ? (
            <Bot className="w-8 h-8" />
          ) : (
            <Camera className="w-8 h-8" />
          )}
        </div>

        {/* Clear Verification Label */}
        <div className={`inline-block px-4 py-1.5 rounded-full border text-xs font-mono font-bold tracking-widest uppercase mb-3 ${
          isSynthetic
            ? "bg-[#c15f3c]/10 border-[#c15f3c]/30 text-[#c15f3c]"
            : "bg-emerald-50 border-emerald-300 text-emerald-800"
        }`}>
          {isSynthetic ? "AI Generated Media Confirmed" : "Authentic Camera Photograph Confirmed"}
        </div>

        {/* Large Heading */}
        <h2 className={`text-2xl sm:text-4xl lg:text-5xl font-extrabold tracking-tight font-sans mb-3 text-center ${
          isSynthetic ? "text-[#c15f3c]" : "text-emerald-900"
        }`}>
          {isSynthetic ? "AI Generated / Synthetic" : "Authentic Real Photograph"}
        </h2>

        {currentData.modelUsed && (
          <div className="mb-4 inline-flex items-center gap-2 px-3.5 py-1 rounded-full bg-[#f4f3ee] border border-[#b1ada1]/35 text-xs font-mono text-[#767167] font-semibold mx-auto">
            <span className={`w-1.5 h-1.5 rounded-full ${isSynthetic ? "bg-[#c15f3c]" : "bg-emerald-500"}`} />
            <span>ENGINE: {currentData.modelUsed}</span>
          </div>
        )}

        {/* Clean Percentage Meters */}
        <div className="flex flex-col sm:flex-row items-center justify-center gap-4 font-mono mb-4">
          <div className="flex items-baseline gap-2">
            <span className="text-[#2b2723]/60 text-sm font-semibold">
              {isSynthetic ? "AI Generation Probability:" : "Real Camera Confidence:"}
            </span>
            <span className={`text-4xl sm:text-5xl font-extrabold ${isSynthetic ? "text-[#c15f3c]" : "text-emerald-700"}`}>
              {synthScore}%
            </span>
          </div>

          {isSynthetic && (
            <div className="flex items-baseline gap-2">
              <span className="text-[#2b2723]/60 text-sm font-semibold">Authentic Photograph:</span>
              <span className="text-4xl sm:text-5xl font-extrabold text-emerald-700">{realScore}%</span>
            </div>
          )}

          {currentData.confidenceTier && (
            <span className={`px-4 py-1.5 rounded-full text-xs font-bold border tracking-wider ${
              isSynthetic
                ? "bg-[#c15f3c]/10 text-[#c15f3c] border-[#c15f3c]/30"
                : "bg-emerald-50 text-emerald-800 border-emerald-300"
            }`}>
              {currentData.confidenceTier}
            </span>
          )}
        </div>

        {/* Plain-English Description */}
        <p className="text-sm sm:text-base text-[#2b2723]/80 max-w-xl mx-auto leading-relaxed mb-6 font-sans text-center">
          {isSynthetic
            ? "Forensic analysis confirmed this image was generated by AI diffusion software. The 2D Fourier Transform shows unnatural lattice artifacts, no physical CMOS sensor noise was detected, and metadata lacks authentic camera hardware provenance."
            : "Physical CMOS sensor noise (PRNU), natural optical lens characteristics, and a continuous 1/f frequency spectrum verified this is an authentic photograph captured by a real camera."
          }
        </p>

        {/* Confidence Meter Bar */}
        <div className="max-w-md mx-auto mb-6">
          <div className="flex items-center justify-between text-[10px] font-mono text-[#767167] mb-1">
            <span>AI Generated</span>
            <span>Authentic Photo</span>
          </div>
          <div className="w-full bg-[#f4f3ee] rounded-full overflow-hidden h-3 border border-[#b1ada1]/30">
            <div
              className={`h-full rounded-full transition-all duration-1000 ease-out ${
                isSynthetic ? "bg-gradient-to-r from-[#c15f3c] to-amber-400" : "bg-gradient-to-r from-emerald-500 to-emerald-700"
              }`}
              style={{ width: `${isSynthetic ? synthScore : realScore}%` }}
            />
          </div>
          <div className="flex items-center justify-between text-[10px] font-mono text-[#767167] mt-1">
            <span>{isSynthetic ? synthScore : realScore}%</span>
            <span>{isSynthetic ? realScore : synthScore}%</span>
          </div>
        </div>

        {/* 3 Action Buttons */}
        <div className="flex flex-wrap items-center justify-center gap-3.5 sm:gap-4 max-w-xl mx-auto">
          <button
            onClick={onAnalyzeAnother}
            className="flex-1 min-w-[170px] py-3.5 px-6 rounded-xl bg-[#f4f3ee] border border-[#b1ada1]/40 hover:bg-white text-[#2b2723] flex items-center justify-center gap-2 text-xs sm:text-sm font-semibold transition-all group"
          >
            <RotateCcw className="w-4 h-4 group-hover:-rotate-90 transition-transform text-[#2b2723]" />
            <span>Scan Another Image</span>
          </button>

          <button
            onClick={onDownloadReport}
            className={`flex-1 min-w-[170px] py-3.5 px-6 rounded-xl text-white flex items-center justify-center gap-2 text-xs sm:text-sm font-semibold transition-all shadow-sm ${
              isSynthetic ? "bg-[#c15f3c] hover:bg-[#c15f3c]/90" : "bg-emerald-700 hover:bg-emerald-800"
            }`}
          >
            <Download className="w-4 h-4" />
            <span>Download Certificate</span>
          </button>

          <button
            onClick={onViewFullAnalysis}
            className="w-full sm:w-auto py-3.5 px-5 rounded-xl bg-white border border-[#b1ada1]/40 hover:bg-[#f4f3ee] text-[#2b2723] flex items-center justify-center gap-2 text-xs sm:text-sm font-semibold transition-all"
          >
            <Eye className="w-4 h-4 text-[#c15f3c]" />
            <span>View Detailed Evidence</span>
          </button>
        </div>

        {/* Cryptographic hash footer */}
        <div className="mt-10 pt-6 border-t border-[#b1ada1]/30 flex flex-wrap items-center justify-between gap-3 text-xs font-mono text-[#2b2723]/60 max-w-xl mx-auto">
          <span>SHA-256: {currentData.sha256?.substring(0, 16)}...</span>
          <span className={`text-[#2b2723] flex items-center gap-1.5 font-semibold`}>
            <CheckCircle2 className={`w-4 h-4 ${isSynthetic ? "text-[#c15f3c]" : "text-emerald-600"}`} />
            Verified by VeriLens Multi-Signal Forensics
          </span>
        </div>

      </div>
    </div>
  );
}
